oci:
  ###############################################################
  # Kubernetes
  - source: registry.k8s.io/kube-apiserver:v1.33.2
    destination: registry.k8s.io/kube-apiserver:v1.33.2
  - source: registry.k8s.io/kube-controller-manager:v1.33.2
    destination: registry.k8s.io/kube-controller-manager:v1.33.2
  - source: registry.k8s.io/kube-scheduler:v1.33.2
    destination: registry.k8s.io/kube-scheduler:v1.33.2
  - source: registry.k8s.io/kube-proxy:v1.33.2
    destination: registry.k8s.io/kube-proxy:v1.33.2
  - source: registry.k8s.io/coredns/coredns:v1.12.1
    destination: registry.k8s.io/coredns:v1.12.1
  - source: registry.k8s.io/pause:3.10
    destination: registry.k8s.io/pause:3.10
  - source: registry.k8s.io/etcd:3.5.21-0
    destination: registry.k8s.io/etcd:3.5.21-0
  ###############################################################
  # Ciliun
  - source: docker.io/library/busybox:1.37.0
    destination: docker.io/library/busybox:1.37.0
  - source: ghcr.io/spiffe/spire-agent:1.9.6
    destination: ghcr.io/spiffe/spire-agent:1.9.6
  - source: ghcr.io/spiffe/spire-server:1.9.6
    destination: ghcr.io/spiffe/spire-server:1.9.6
  - source: quay.io/cilium/certgen:v0.3.1
    destination: quay.io/cilium/certgen:v0.3.1
  - source: quay.io/cilium/cilium-ci:latest
    destination: quay.io/cilium/cilium-ci:latest
  - source: quay.io/cilium/cilium-envoy:v1.35.3-1763805254-768d5a2892ffd7012014681e8a7547124e57fc53
    destination: quay.io/cilium/cilium-envoy:v1.35.3-1763805254-768d5a2892ffd7012014681e8a7547124e57fc53
  - source: quay.io/cilium/clustermesh-apiserver-ci:latest
    destination: quay.io/cilium/clustermesh-apiserver-ci:latest
  - source: quay.io/cilium/hubble-relay-ci:latest
    destination: quay.io/cilium/hubble-relay-ci:latest
  - source: quay.io/cilium/hubble-ui:v0.13.3
    destination: quay.io/cilium/hubble-ui:v0.13.3
  - source: quay.io/cilium/hubble-ui-backend:v0.13.3
    destination: quay.io/cilium/hubble-ui-backend:v0.13.3
  - source: quay.io/cilium/operator-generic:v1.18.1
    destination: quay.io/cilium/operator-generic:v1.18.1
  - source: quay.io/cilium/startup-script:1763560095-8f36c34
    destination: quay.io/cilium/startup-script:1763560095-8f36c34
