oci:
  - ghcr.io/jacobweinstock/waitdaemon:latest
  - quay.io/tinkerbell/actions/image2disk:latest
  - quay.io/tinkerbell/actions/kexec:latest
  - quay.io/tinkerbell/actions/writefile:latest
  - ghcr.io/tinkerbell/tink-agent:v0.19.1
